//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string CallbackDetail { get; set; }
        public string CreateOn { get; set; }
        public string UpdateOn { get; set; }
        public Nullable<long> Pin { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CityCode { get; set; }
        public string StateCode { get; set; }
    }
}
