//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOutcome
    {
        public string ID { get; set; }
        public string SubOutcomeName { get; set; }
    
        public virtual Outcome Outcome { get; set; }
    }
}
